AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Secrets Manager for CloudKnox

Parameters:
  serviceId:
    Description: >-
      REQUIRED. Default Service Account ID for CloudKnox
    Type: String
    AllowedPattern: .+
    Default: "SA28FPC69M5WZANP"
    ConstraintDescription: serviceId is required
  apiId:
    Description: >-
      REQUIRED. Default API ID for CloudKnox
    Type: String
    AllowedPattern: .+
    Default: "21564ec10f7943d7eb031e74e69f1abc"
    ConstraintDescription: api Id is required
  accessToken:
    Description: >-
      REQUIRED. Default Access Token for CloudKnox
    Type: String
    AllowedPattern: .+
    Default: "ee82f50913ecf427833938c0112be9a7711f91a5252b42c4ab432391c7aad77c8a0bd3ffb7d69932613251d8c33dfd88c0bd36cf2720265275f626518922455a"
    ConstraintDescription: access Token is required
  url:
    Description: >-
      REQUIRED. Default url for CloudKnox
    Type: String
    AllowedPattern: .+
    Default: "app.cloudknox.io"
    ConstraintDescription: url is required

Resources:

  CloudKnoxSecretString:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Credentials required for CloudKnox
      Name: CloudKnoxSecretString
      SecretString:
        Fn::Join:
        - ''
        - - '{"serviceId":"'
          - Ref: serviceId
          - '","apiId": "'
          - Ref: apiId
          - '","accessToken": "'
          - Ref: accessToken
          - '","url": "'
          - Ref: url
          - '","accountId": "'
          - Ref: AWS::AccountId
          - '"}'
  